name: your_drip
description: "A new hobby project"

publish_to: 'none' # Remove this line if you wish to publis

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  ui_core:
    path: .././ui_core
  material_shapes:
    path: material_shapes
  
  hydrated_bloc: ^10.0.0
  go_router: ^15.1.3
  path_provider: ^2.1.5
  get_it: ^8.0.3
  hive: ^2.2.3
  responsive_sizer: ^3.3.1
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  

  assets:
    - assets/icons/
    - assets/images/
    - assets/lottie/
    - assets/fonts/

  fonts:
    
      - family: Jost
        fonts:
          - asset: assets/fonts/Jost-Regular.ttf
      - family: Oddval
        fonts:
          - asset: assets/fonts/Oddval-SemiBold.ttf
         
          
          